Repository depromeet/ygtang-server, pull requests merged in 2022-05, with the labels that each got.

#22 이메일 인증, 회원가입, 로그인 리팩토링 및 리프레시 토큰 재발급 기능 추가
  module-api/src/main/java/inspiration/ResultResponse.java
  module-api/src/main/java/inspiration/auth/AuthService.java
  module-api/src/main/java/inspiration/auth/CustomUserDetailsService.java
  module-api/src/main/java/inspiration/auth/request/TokenRequest.java
  module-api/src/main/java/inspiration/auth/response/TokenResponse.java
  module-api/src/main/java/inspiration/emailauth/EmailAuthService.java
  module-api/src/main/java/inspiration/emailauth/EmailSendService.java
  module-api/src/main/java/inspiration/emailauth/request/AuthenticateEmailRequest.java
  module-api/src/main/java/inspiration/emailauth/request/EmailAuthRequest.java
  module-api/src/main/java/inspiration/emailauth/request/SendEmailRequest.java
  module-api/src/main/java/inspiration/member/MemberService.java
  module-api/src/main/java/inspiration/member/ResultCode.java
  module-api/src/main/java/inspiration/member/ResultResponse.java
  module-api/src/main/java/inspiration/member/response/NicknameResponse.java
  module-common/src/main/java/inspiration/config/SwaggerConfig.java
  module-common/src/main/java/inspiration/config/security/JwtProvider.java
  module-common/src/main/java/inspiration/config/security/SecurityConfiguration.java
  module-common/src/main/java/inspiration/config/security/TokenResponse.java
  module-common/src/main/java/inspiration/enumeration/ExceptionType.java
  module-common/src/main/java/inspiration/enumeration/ExpireTimeConstants.java
  module-common/src/main/java/inspiration/enumeration/HttpHeaderType.java
  module-common/src/main/java/inspiration/enumeration/TokenType.java
  module-common/src/main/java/inspiration/exception/RefreshTokenException.java
  module-domain/src/main/java/inspiration/emailauth/EmailAuth.java
  module-domain/src/main/java/inspiration/emailauth/EmailAuthRepository.java
  module-domain/src/main/java/inspiration/member/Member.java
  module-domain/src/main/java/inspiration/member/MemberRepository.java
  module-web/src/main/java/inspiration/v1/ResultResponse.java
  module-web/src/main/java/inspiration/v1/advice/ErrorResponse.java
  module-web/src/main/java/inspiration/v1/advice/GlobalExceptionController.java
  module-web/src/main/java/inspiration/v1/member/MemberController.java
  module-web/src/main/java/inspiration/v1/reissue/ReissueController.java
  module-web/src/main/resources/db/migration/V1__create_email_auth_table.sql
  module-web/src/main/resources/db/migration/V2__cteate_member_table.sql
  module-web/src/main/resources/db/migration/V3__create_member_roles_table.sql
  module-web/src/main/resources/db/migration/V4__alter_email_auth_add_constraint.sql
  module-web/src/main/resources/db/migration/V5__alter_member_add_constraint_email.sql
  module-web/src/main/resources/db/migration/V5__insert_dymmy_test_uesr.sql
  module-web/src/main/resources/db/migration/V6__alter_member_add_constraint_nickname.sql
  module-web/src/main/resources/db/migration/V7__alter_member_roles_references_member.sql
Labels: feature, refactor

#25 영감, 태그 관련 기능 / AuthenticationPrincipalArgumentResolver 추가에 따른 WebConfig 수정 / 패턴에 따른 security 인증처리
  module-api/build.gradle
  module-api/src/main/java/inspiration/aws/AwsS3Config.java
  module-api/src/main/java/inspiration/aws/AwsS3Service.java
  module-api/src/main/java/inspiration/inspiration/InspirationService.java
  module-api/src/main/java/inspiration/inspiration/request/InspirationAddRequest.java
  module-api/src/main/java/inspiration/inspiration/request/InspirationModifyRequest.java
  module-api/src/main/java/inspiration/inspiration/request/InspirationTagRequest.java
  module-api/src/main/java/inspiration/inspiration/response/InspirationResponse.java
  module-api/src/main/java/inspiration/member/MemberService.java
  module-api/src/main/java/inspiration/member/response/MemberResponse.java
  module-api/src/main/java/inspiration/tag/TagService.java
  module-api/src/main/java/inspiration/tag/request/TagAddRequest.java
  module-api/src/main/java/inspiration/tag/response/TagResponse.java
  module-common/src/main/java/inspiration/config/AuthenticationPrincipal.java
  module-common/src/main/java/inspiration/config/AuthenticationPrincipalArgumentResolver.java
  module-common/src/main/java/inspiration/config/WebConfig.java
  module-common/src/main/java/inspiration/config/security/JwtAuthenticationFilter.java
  module-common/src/main/java/inspiration/config/security/SecurityConfiguration.java
  module-common/src/main/java/inspiration/enumeration/ExceptionType.java
  module-common/src/main/java/inspiration/exception/ConflictRequestException.java
  module-common/src/main/java/inspiration/exception/EmailAuthenticatedTimeExpiredException.java
  module-common/src/main/java/inspiration/exception/EmailNotAuthenticatedException.java
  module-common/src/main/java/inspiration/exception/InvalidMemberException.java
  module-common/src/main/java/inspiration/exception/InvalidTokenException.java
  module-common/src/main/java/inspiration/exception/NoAccessAuthorizationException.java
  module-common/src/main/java/inspiration/exception/PostNotFoundException.java
  module-common/src/main/java/inspiration/exception/ResourceNotFoundException.java
  module-common/src/main/java/inspiration/exception/UnauthorizedAccessRequestException.java
  module-domain/src/main/java/inspiration/date/BaseTimeEntity.java
  module-domain/src/main/java/inspiration/inspiration/Inspiration.java
  module-domain/src/main/java/inspiration/inspiration/InspirationRepository.java
  module-domain/src/main/java/inspiration/inspiration/InspirationType.java
  module-domain/src/main/java/inspiration/inspiration_tag/InspirationTag.java
  module-domain/src/main/java/inspiration/inspiration_tag/InspirationTagRepository.java
  module-domain/src/main/java/inspiration/member/Member.java
  module-domain/src/main/java/inspiration/tag/Tag.java
  module-domain/src/main/java/inspiration/tag/TagRepository.java
  module-web/build.gradle
  module-web/src/main/java/inspiration/Application.java
  module-web/src/main/java/inspiration/v1/ResultResponse.java
  module-web/src/main/java/inspiration/v1/advice/GlobalExceptionController.java
  module-web/src/main/java/inspiration/v1/inspiration/InspirationController.java
  module-web/src/main/java/inspiration/v1/tag/TagController.java
  module-web/src/main/resources/application-dev.yml
  module-web/src/main/resources/application-local.yml
  module-web/src/main/resources/application.yml
  module-web/src/main/resources/db/migration/V10__create_inspiration_tag_table.sql
  module-web/src/main/resources/db/migration/V11__add_inspiration_foreignkey.sql
  module-web/src/main/resources/db/migration/V8__create_inspiration_table.sql
  module-web/src/main/resources/db/migration/V9__create_tag_table.sql
Labels: feature

#27 feat: 이메일 인증 상태를 확인하고 상태를 반환하는 api 추가
  module-api/src/main/java/inspiration/emailauth/EmailAuthService.java
  module-web/src/main/java/inspiration/v1/member/MemberController.java
Labels: feature

#35 feat: 영감, 태그 관련 기능 추가
  module-api/build.gradle
  module-api/src/main/java/inspiration/RestPage.java
  module-api/src/main/java/inspiration/inspiration/InspirationService.java
  module-api/src/main/java/inspiration/inspiration/request/InspirationAddRequest.java
  module-api/src/main/java/inspiration/inspiration/response/InspirationResponse.java
  module-api/src/main/java/inspiration/inspiration/response/OpenGraphResponse.java
  module-api/src/main/java/inspiration/inspiration_tag/InspirationTagService.java
  module-api/src/main/java/inspiration/tag/TagService.java
  module-api/src/main/java/inspiration/tag/response/TagResponse.java
  module-common/build.gradle
  module-common/src/main/java/inspiration/config/CacheConfig.java
  module-common/src/main/java/inspiration/config/security/FeignConfigurationFactory.java
  module-domain/src/main/java/inspiration/inspiration/Inspiration.java
  module-domain/src/main/java/inspiration/inspiration_tag/InspirationTag.java
  module-domain/src/main/java/inspiration/inspiration_tag/InspirationTagRepository.java
  module-domain/src/main/java/inspiration/tag/Tag.java
  module-domain/src/main/java/inspiration/tag/TagRepository.java
  module-web/src/main/java/inspiration/Application.java
  module-web/src/main/java/inspiration/v1/inspiration/InspirationController.java
  module-web/src/main/java/inspiration/v1/tag/TagController.java
  module-web/src/main/resources/application-dev.yml
  module-web/src/main/resources/application-local.yml
Labels: feature

#34 feat : 패스워드 변경을 위한 이메일 인증 및 패스워드 변경 기능 추가
  module-api/src/main/java/inspiration/auth/AuthService.java
  module-api/src/main/java/inspiration/emailauth/EmailAuthService.java
  module-api/src/main/java/inspiration/emailauth/EmailSendService.java
  module-api/src/main/java/inspiration/emailauth/SignUpEmailSendService.java
  module-api/src/main/java/inspiration/emailauth/UpdatePasswordEmailSendService.java
  module-api/src/main/java/inspiration/member/MemberService.java
  module-api/src/main/java/inspiration/member/request/SignUpRequest.java
  module-api/src/main/java/inspiration/member/request/UpdatePasswordRequest.java
  module-api/src/main/java/inspiration/signup/SignupService.java
  module-common/src/main/java/inspiration/config/security/SecurityConfiguration.java
  module-common/src/main/java/inspiration/enumeration/ExceptionType.java
  module-common/src/main/java/inspiration/enumeration/ExpireTimeConstants.java
  module-common/src/main/java/inspiration/enumeration/RedisKey.java
  module-common/src/main/java/inspiration/property/MailProperties.java
  module-domain/src/main/java/inspiration/member/Member.java
  module-web/src/main/java/inspiration/Application.java
  module-web/src/main/java/inspiration/v1/auth/AuthController.java
  module-web/src/main/java/inspiration/v1/member/MemberController.java
  module-web/src/main/java/inspiration/v1/reissue/ReissueController.java
  module-web/src/main/java/inspiration/v1/signup/SignUpController.java
  module-web/src/main/resources/application-dev.yml
  module-web/src/main/resources/application-local.yml
  module-web/src/main/resources/application.yml
Labels: feature

#40 Ressiue Api Refactor
  module-api/src/main/java/inspiration/auth/AuthService.java
  module-common/src/main/java/inspiration/config/security/JwtProvider.java
  module-web/src/main/java/inspiration/v1/reissue/ReissueController.java
Labels: refactor

#55 비밀번호 초기화 링크 클릭시 app view로 redirect
  module-api/src/main/java/inspiration/emailauth/EmailAuthService.java
  module-common/src/main/java/inspiration/utils/PasswordAuthRedirectViewUtil.java
Labels: feature
