Repository depromeet/ygtang-server, pull requests merged in 2022-08, with the labels that each got.

#132 feat: docker 설정 변경, health check 추가
  build.gradle
  docker-compose.yml
  scripts/health_check.sh
  scripts/run_new_was.sh
Labels: refactor

#155 feat: docker build를 위한 AWS CodeBuild 환경 연동
  .github/workflows/dev_deploy.yml
  appspec.yml
  docker-compose.yml
  scripts/deploy.sh
  scripts/login_ecr.sh
Labels: refactor

#176 Feature/120 codebuild deploy
  build.gradle
  module-web/build.gradle
Labels: chore

#170 docs: readme owner에 해성님 추가
  README.md
Labels: documentation
